import cherrypy
import json
import datetime

class CatalogExpose:
    exposed = True
    def __init__(self):
        self.deviceList = []
        self.vaseList = []

    def save_to_file(self):
        with open('resource_catalog.json', 'w') as file:
            json.dump({"deviceList": self.deviceList, "vaseList": self.vaseList}, file)


    @cherrypy.tools.json_out()
    def GET(self, *args, **kwargs):
        print(args)
        if args[0] == 'deviceList':
            return self.deviceList
        elif args[0] == 'vaseList':
            return self.vaseList
        elif args[0].startswith('device'):
            for device in self.deviceList:
                if device["device_id"] == args[1]:
                    return device
            return {}
        elif args[0].startswith('vase'):
            for vase in self.vaseList:
                if vase["vase_id"] == args[1]:
                    return vase
            return {}
        else:
            return {"message": "Invalid resource"}



    ''''
        body example of a device POST request
        {
            "device_id": "2345",
            "device_name": "vase_sensors_2345",
            "device_type": "vase_sensors_build_0.1",
            "measureType": [
                "soil_moisture",
                "watertank_level",
                "temperature",
                "light_level"
            ],
            "availableServices": [
                "MQTT",
                "REST"
            ],
            "servicesDetails": [
                {
                    "serviceType": "MQTT",
                    "topic": [
                        "smartPlant/2345/sensors"
                    ]
                }
            ]
        }
        
        body example of a vase POST request
        "vase_id": "1" generated by the system incrementally,
        "lastUpdate": generated by the system
        the name is given by the user
        {
            "vase_name": "vase1", 
            "vase_user": "user123",                                         
            "vase_status": "disabled",
            "plant": null,
            "deviceList": [
                "2345"
            ]  
        }
        
    
    '''
    @cherrypy.tools.json_in()
    @cherrypy.tools.json_out()
    def POST(self, *args, **kwargs):
        if args[0] == 'device':
            device = cherrypy.request.json
            this_time = datetime.datetime.now()
            device["lastUpdate"] = this_time.strftime("%Y-%m-%d %H:%M:%S")
            self.deviceList.append(device)
            self.save_to_file()
            return {"message": "Device added successfully"}
        elif args[0] == 'vase':
            vase = cherrypy.request.json
            this_id = int(self.vaseList[-1]["vase_id"]) + 1
            this_time = datetime.datetime.now()
            vase["vase_id"] = str(this_id)
            vase["lastUpdate"] = this_time.strftime("%Y-%m-%d %H:%M:%S")
            self.vaseList.append(vase)
            self.save_to_file()
            return {"message": "Vase added successfully",
                    "id": this_id}
        else:
            return {"message": "Invalid resource"}


    @cherrypy.tools.json_in()
    @cherrypy.tools.json_out()
    def PUT(self, *args, **kwargs):
        if args[0].startswith('device'):
            device_id = args[1]
            device = cherrypy.request.json
            for i, d in enumerate(self.deviceList):
                if d["device_id"] == device_id:
                    self.deviceList[i] = device
                    self.save_to_file()
                    return {"message": "Device updated successfully"}
            return {"message": "Device not found"}
        elif args[0].startswith('vase'):
            vase_id = args[1]
            vase = cherrypy.request.json
            for i, v in enumerate(self.vaseList):
                if v["vase_id"] == vase_id:
                    self.vaseList[i] = vase
                    self.save_to_file()
                    return {"message": "Vase updated successfully"}
            return {"message": "Vase not found"}
        else:
            return {"message": "Invalid resource"}

if __name__ == '__main__':
    with open('./resource_catalog.json', 'r') as file:
        data = json.load(file)
        catalog = CatalogExpose()
        catalog.deviceList = data["deviceList"]
        catalog.vaseList = data["vaseList"]
        conf = {
        '/':{
            'request.dispatch': cherrypy.dispatch.MethodDispatcher(),
            'tools.sessions.on' : True
        }
        }
        cherrypy.config.update({
            'server.socket_host': '0.0.0.0',
            'server.socket_port': 8081  # Specify your desired port here
        })
        cherrypy.tree.mount(catalog, '/', conf)
        cherrypy.engine.start()
        cherrypy.engine.block()
